"""reconcile model drift

Revision ID: f82228b12b1f
Revises: e37413e590b2
Create Date: 2026-06-14 14:36:11.659087
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f82228b12b1f'
down_revision: Union[str, None] = 'e37413e590b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_workspace_memories_workspace'), table_name='workspace_memories')
    op.drop_table('workspace_memories')
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_chats', 'mode',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'rag'::character varying"))
    op.alter_column('ai_chats', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_chats', 'node_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'branch'::character varying"))
    op.alter_column('ai_chats', 'description',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_chats', 'summary',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_chats', 'chat_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('ai_chats', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_chats', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('ai_chats_local_id_key'), 'ai_chats', type_='unique')
    op.drop_index(op.f('idx_ai_chats_card'), table_name='ai_chats')
    op.drop_index(op.f('idx_ai_chats_local_id'), table_name='ai_chats')
    op.drop_index(op.f('idx_ai_chats_workspace'), table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_workspace_parent'), table_name='ai_chats')
    op.create_index(op.f('ix_ai_chats_card_id'), 'ai_chats', ['card_id'], unique=False)
    op.create_index(op.f('ix_ai_chats_local_id'), 'ai_chats', ['local_id'], unique=True)
    op.create_index(op.f('ix_ai_chats_workspace_id'), 'ai_chats', ['workspace_id'], unique=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('branch_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_branch_insights_target'), table_name='branch_insights')
    op.create_index(op.f('ix_branch_insights_target_chat_id'), 'branch_insights', ['target_chat_id'], unique=False)
    op.alter_column('card_relations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('card_relations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('cards', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'#B8D4E3'::character varying"))
    op.alter_column('cards', 'emotion_tag',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cards', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cards', 'is_temp',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('cards_local_id_key'), 'cards', type_='unique')
    op.drop_index(op.f('idx_cards_embedding'), table_name='cards', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_cards_fts'), table_name='cards', postgresql_using='gin')
    op.drop_index(op.f('idx_cards_keywords'), table_name='cards', postgresql_using='gin')
    op.drop_index(op.f('idx_cards_local_id'), table_name='cards')
    op.drop_index(op.f('idx_cards_workspace'), table_name='cards')
    op.create_index(op.f('ix_cards_local_id'), 'cards', ['local_id'], unique=True)
    op.create_index(op.f('ix_cards_workspace_id'), 'cards', ['workspace_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_chat_messages_chat'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_chat_id'), 'chat_messages', ['chat_id'], unique=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_comments_card'), table_name='comments')
    op.create_index(op.f('ix_comments_card_id'), 'comments', ['card_id'], unique=False)
    op.alter_column('node_cards', 'chat_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_notifications_user_unread'), table_name='notifications')
    op.alter_column('synthesis_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('topic_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_topic_cards_card'), table_name='topic_cards')
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_topics_centroid'), table_name='topics', postgresql_ops={'centroid': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.drop_index(op.f('idx_topics_workspace'), table_name='topics')
    op.create_index(op.f('ix_topics_workspace_id'), 'topics', ['workspace_id'], unique=False)
    op.alter_column('user_settings', 'ai_provider',
               existing_type=sa.VARCHAR(length=32),
               nullable=False,
               existing_server_default=sa.text("'deepseek'::character varying"))
    op.alter_column('user_settings', 'ai_model',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_settings', 'ai_tone',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'创意'::character varying"))
    op.alter_column('user_settings', 'ai_direction',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'发散'::character varying"))
    op.alter_column('user_settings', 'agent_sensitivity',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'中'::character varying"))
    op.alter_column('user_settings', 'walk_sensitivity',
               existing_type=sa.VARCHAR(length=8),
               nullable=False,
               existing_server_default=sa.text("'高'::character varying"))
    op.alter_column('user_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               nullable=False,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_users_openid'), table_name='users')
    op.drop_constraint(op.f('users_wechat_openid_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_wechat_openid'), 'users', ['wechat_openid'], unique=True)
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'editor'::character varying"))
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'icon',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'💡'::character varying"))
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=False,
               existing_server_default=sa.text("'#94B4C8'::character varying"))
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_workspaces_local_id'), table_name='workspaces')
    op.drop_index(op.f('idx_workspaces_owner'), table_name='workspaces')
    op.drop_constraint(op.f('workspaces_local_id_key'), 'workspaces', type_='unique')
    op.create_index(op.f('ix_workspaces_local_id'), 'workspaces', ['local_id'], unique=True)
    op.drop_column('workspaces', 'invite_code_expires_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('invite_code_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_workspaces_local_id'), table_name='workspaces')
    op.create_unique_constraint(op.f('workspaces_local_id_key'), 'workspaces', ['local_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_workspaces_owner'), 'workspaces', ['owner_id'], unique=False)
    op.create_index(op.f('idx_workspaces_local_id'), 'workspaces', ['local_id'], unique=False)
    op.alter_column('workspaces', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspaces', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'#94B4C8'::character varying"))
    op.alter_column('workspaces', 'icon',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'💡'::character varying"))
    op.alter_column('workspace_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('workspace_members', 'role',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'editor'::character varying"))
    op.drop_index(op.f('ix_users_wechat_openid'), table_name='users')
    op.create_unique_constraint(op.f('users_wechat_openid_key'), 'users', ['wechat_openid'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_openid'), 'users', ['wechat_openid'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'avatar_url',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_settings', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_settings', 'walk_sensitivity',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'高'::character varying"))
    op.alter_column('user_settings', 'agent_sensitivity',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'中'::character varying"))
    op.alter_column('user_settings', 'ai_direction',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'发散'::character varying"))
    op.alter_column('user_settings', 'ai_tone',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'创意'::character varying"))
    op.alter_column('user_settings', 'ai_model',
               existing_type=sa.VARCHAR(length=64),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('user_settings', 'ai_provider',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("'deepseek'::character varying"))
    op.drop_index(op.f('ix_topics_workspace_id'), table_name='topics')
    op.create_index(op.f('idx_topics_workspace'), 'topics', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_topics_centroid'), 'topics', ['centroid'], unique=False, postgresql_ops={'centroid': 'vector_cosine_ops'}, postgresql_with={'lists': '50'}, postgresql_using='ivfflat')
    op.alter_column('topics', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('topics', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('idx_topic_cards_card'), 'topic_cards', ['card_id'], unique=True)
    op.alter_column('topic_cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('synthesis_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_notifications_user_unread'), 'notifications', ['user_id', 'is_read'], unique=False)
    op.alter_column('notifications', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('node_cards', 'chat_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_comments_card_id'), table_name='comments')
    op.create_index(op.f('idx_comments_card'), 'comments', ['card_id'], unique=False)
    op.alter_column('comments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chat_messages_chat_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_chat'), 'chat_messages', ['chat_id'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cards_workspace_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_local_id'), table_name='cards')
    op.create_index(op.f('idx_cards_workspace'), 'cards', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_cards_local_id'), 'cards', ['local_id'], unique=False)
    op.create_index(op.f('idx_cards_keywords'), 'cards', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_cards_fts'), 'cards', ['fts_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_cards_embedding'), 'cards', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_unique_constraint(op.f('cards_local_id_key'), 'cards', ['local_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('cards', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cards', 'is_temp',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('cards', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cards', 'emotion_tag',
               existing_type=sa.VARCHAR(length=32),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('cards', 'color',
               existing_type=sa.VARCHAR(length=16),
               nullable=True,
               existing_server_default=sa.text("'#B8D4E3'::character varying"))
    op.alter_column('cards', 'keywords',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    op.alter_column('cards', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('card_relations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('card_relations', 'score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.drop_index(op.f('ix_branch_insights_target_chat_id'), table_name='branch_insights')
    op.create_index(op.f('idx_branch_insights_target'), 'branch_insights', ['target_chat_id', 'consumed'], unique=False)
    op.alter_column('branch_insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_ai_chats_workspace_id'), table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_local_id'), table_name='ai_chats')
    op.drop_index(op.f('ix_ai_chats_card_id'), table_name='ai_chats')
    op.create_index(op.f('ix_ai_chats_workspace_parent'), 'ai_chats', ['workspace_id', 'parent_id'], unique=False)
    op.create_index(op.f('idx_ai_chats_workspace'), 'ai_chats', ['workspace_id'], unique=False)
    op.create_index(op.f('idx_ai_chats_local_id'), 'ai_chats', ['local_id'], unique=False)
    op.create_index(op.f('idx_ai_chats_card'), 'ai_chats', ['card_id'], unique=False)
    op.create_unique_constraint(op.f('ai_chats_local_id_key'), 'ai_chats', ['local_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('ai_chats', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('ai_chats', 'extra',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('ai_chats', 'sort_order',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('ai_chats', 'chat_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('ai_chats', 'summary',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_chats', 'description',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("''::text"))
    op.alter_column('ai_chats', 'node_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'branch'::character varying"))
    op.alter_column('ai_chats', 'title',
               existing_type=sa.VARCHAR(length=128),
               nullable=True,
               existing_server_default=sa.text("''::character varying"))
    op.alter_column('ai_chats', 'mode',
               existing_type=sa.VARCHAR(length=8),
               nullable=True,
               existing_server_default=sa.text("'rag'::character varying"))
    op.alter_column('activity_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('workspace_memories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('workspace_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('source_chat_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_chat_id'], ['ai_chats.id'], name=op.f('workspace_memories_source_chat_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('workspace_memories_workspace_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('workspace_memories_pkey')),
    sa.UniqueConstraint('workspace_id', 'slug', name=op.f('uq_workspace_memory_slug'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_workspace_memories_workspace'), 'workspace_memories', ['workspace_id'], unique=False)
    # ### end Alembic commands ###
