const DEFAULT_KEYWORDS = ['灵感'];

const CARD_COLORS = ['#B8D4E3', '#C4D7B2', '#E8C9A0', '#D4B5D0', '#A0B8C8', '#D4C5A9'];

const mockCards = [
  {
    id: 'card_001',
    content: '或许可以用声音交互来代替文字输入，让灵感记录更快速自然，像和朋友聊天一样记录想法',
    title: '语音灵感输入',
    keywords: ['语音交互', '灵感记录', '自然输入'],
    emotionTag: '',
    color: '#B8D4E3',
    createdAt: '2026-04-25 22:30',
    updatedAt: null,
    isFavorite: true,
    isTemp: false,
    relatedIds: ['card_002'],
    agentRecommendIds: ['card_003', 'card_005'],
    hasAiChat: true,
  },
  {
    id: 'card_002',
    content: '产品设计要遵循"少即是多"的原则，减少不必要的功能入口，让核心体验更突出',
    title: '设计原则',
    keywords: ['产品设计', '极简主义', '用户体验'],
    emotionTag: '',
    color: '#C4D7B2',
    createdAt: '2026-04-25 18:15',
    updatedAt: '2026-04-25 20:00',
    isFavorite: false,
    isTemp: false,
    relatedIds: ['card_001'],
    agentRecommendIds: ['card_004'],
    hasAiChat: false,
  },
  {
    id: 'card_003',
    content: '色彩心理学：莫兰迪色系传递宁静优雅，低饱和色彩有助于专注思考',
    title: '',
    keywords: ['色彩心理学', '莫兰迪色', '专注'],
    emotionTag: '',
    color: '#D4B5D0',
    createdAt: '2026-04-24 23:45',
    updatedAt: null,
    isFavorite: false,
    isTemp: true,
    relatedIds: [],
    agentRecommendIds: ['card_001', 'card_006'],
    hasAiChat: false,
  },
  {
    id: 'card_004',
    content: '做一个灵感地图功能，用地图的形式展示灵感之间的关联，可视化思维脉络',
    title: '灵感地图',
    keywords: ['灵感地图', '可视化', '思维脉络'],
    emotionTag: '',
    color: '#D4C5A9',
    createdAt: '2026-04-24 16:20',
    updatedAt: null,
    isFavorite: true,
    isTemp: false,
    relatedIds: ['card_002', 'card_006'],
    agentRecommendIds: ['card_001'],
    hasAiChat: true,
  },
  {
    id: 'card_005',
    content: '凌晨三点的城市有种特别的宁静感，适合思考人生方向',
    title: '',
    keywords: ['深夜思考', '人生方向', '宁静'],
    emotionTag: '',
    color: '#A0B8C8',
    createdAt: '2026-04-24 03:00',
    updatedAt: null,
    isFavorite: false,
    isTemp: true,
    relatedIds: [],
    agentRecommendIds: ['card_003'],
    hasAiChat: false,
  },
  {
    id: 'card_006',
    content: '把碎片化的想法串联起来，形成一个完整的故事线或产品方案',
    title: '',
    keywords: ['碎片整合', '故事线', '产品方案'],
    emotionTag: '',
    color: '#E8C9A0',
    createdAt: '2026-04-23 21:10',
    updatedAt: null,
    isFavorite: false,
    isTemp: false,
    relatedIds: ['card_004'],
    agentRecommendIds: ['card_002', 'card_005'],
    hasAiChat: true,
  },
  {
    id: 'card_007',
    content: '用户行为数据可以用来优化推荐算法，让灵感关联更精准',
    title: '',
    keywords: ['推荐算法', '用户行为', '数据驱动'],
    emotionTag: '',
    color: '#C4D7B2',
    createdAt: '2026-04-23 14:30',
    updatedAt: null,
    isFavorite: false,
    isTemp: true,
    relatedIds: [],
    agentRecommendIds: ['card_001'],
    hasAiChat: false,
  },
  {
    id: 'card_008',
    content: '在卡片上添加情绪标记，帮助后续复盘时理解当时的心理状态，这对创意复盘很有价值',
    title: '情绪标记',
    keywords: ['情绪标记', '复盘', '心理状态'],
    emotionTag: '',
    color: '#E8C9A0',
    createdAt: '2026-04-22 09:45',
    updatedAt: null,
    isFavorite: true,
    isTemp: false,
    relatedIds: ['card_003', 'card_005'],
    agentRecommendIds: [],
    hasAiChat: false,
  },
  {
    id: 'card_009',
    content: '每日灵感推送：根据历史记录推送相关灵感，帮助用户回顾和深化',
    title: '',
    keywords: ['每日推送', '灵感回顾', '历史关联'],
    emotionTag: '',
    color: '#D4C5A9',
    createdAt: '2026-04-21 17:00',
    updatedAt: null,
    isFavorite: false,
    isTemp: false,
    relatedIds: [],
    agentRecommendIds: ['card_007'],
    hasAiChat: false,
  },
  {
    id: 'card_010',
    content: '灵感碰撞：随机抽取两张卡片，让AI分析潜在关联，激发新思路',
    title: '',
    keywords: ['灵感碰撞', '随机关联', 'AI分析'],
    emotionTag: '',
    color: '#B8D4E3',
    createdAt: '2026-04-20 12:30',
    updatedAt: null,
    isFavorite: false,
    isTemp: true,
    relatedIds: [],
    agentRecommendIds: ['card_004', 'card_009'],
    hasAiChat: false,
  },
];

const mockChats = [
  {
    id: 'chat_001',
    cardId: 'card_001',
    title: '语音灵感输入思路拓展',
    createdAt: '2026-04-25 22:35',
    messages: [
      {
        id: 'msg_001',
        role: 'user',
        content: '如何完善这个语音灵感输入的想法？',
        time: '22:35',
      },
      {
        id: 'msg_002',
        role: 'ai',
        content: '这个想法很有潜力！可以从以下几个方向完善：\n\n1. **语音识别集成**：利用微信小程序的录音API，实现实时语音转文字\n2. **智能分段**：自动识别语音中的停顿，将长段语音拆分为多个灵感点\n3. **情绪识别**：通过语音语调分析当时的情绪状态，自动标记情绪标签\n4. **快捷指令**：支持语音指令如"标记重要"、"关联到xxx"\n\n你觉得哪个方向最有价值？',
        time: '22:36',
      },
      {
        id: 'msg_003',
        role: 'user',
        content: '情绪识别这个方向很有意思，可以结合情绪标签功能',
        time: '22:38',
      },
      {
        id: 'msg_004',
        role: 'ai',
        content: '很好的结合点！情绪识别 + 情绪标签可以形成一个自动化流程：\n\n用户录音 → 语音转文字 → 语调分析 → 自动标记情绪标签 → 生成灵感卡片\n\n这样用户只需要说一句话，系统就能自动完成分类标记，真正实现"1秒闪记"的体验。',
        time: '22:39',
      },
    ],
  },
  {
    id: 'chat_002',
    cardId: 'card_004',
    title: '灵感地图可视化方案',
    createdAt: '2026-04-24 16:25',
    messages: [
      {
        id: 'msg_005',
        role: 'user',
        content: '这个灵感地图功能应该怎么设计？',
        time: '16:25',
      },
      {
        id: 'msg_006',
        role: 'ai',
        content: '灵感地图可以从这几个维度设计：\n\n1. **力导向图**：关联越紧密的卡片距离越近\n2. **时间轴模式**：按创建时间展开，展示思维演变\n3. **主题聚类**：自动按主题分组，形成灵感星系\n\n建议先用简单的节点连线图实现，后续再迭代更复杂的可视化。',
        time: '16:26',
      },
    ],
  },
  {
    id: 'chat_003',
    cardId: 'card_006',
    title: '碎片化想法串联',
    createdAt: '2026-04-23 21:15',
    messages: [
      {
        id: 'msg_007',
        role: 'user',
        content: '帮我拓展这个想法，如何更好地串联碎片化灵感？',
        time: '21:15',
      },
      {
        id: 'msg_008',
        role: 'ai',
        content: '串联碎片化灵感可以从这些角度入手：\n\n1. **关键词桥接**：提取每张卡片的关键词，自动发现隐含关联\n2. **时间脉络**：按时间线展示灵感的演变，发现思维趋势\n3. **互补发现**：找到内容互补的卡片对，建议合并\n4. **AI引导关联**：当新灵感与历史灵感有关联时，主动提醒\n\n核心是让用户用最少的操作看到灵感的全景。',
        time: '21:16',
      },
    ],
  },
];

module.exports = {
  DEFAULT_KEYWORDS,
  CARD_COLORS,
  mockCards,
  mockChats,
};
